/* ============================================================
   LAB REPORTS
   ============================================================ */

function generateReport() {
  const name = document.getElementById('repName').value || '(not provided)';
  const sid = document.getElementById('repId').value || '(not provided)';
  const title = document.getElementById('repTitle').value || 'Network Simulation Experiment';
  const obs = document.getElementById('repObs').value || '(no observations recorded)';
  const lastLog = dashStats.lastRun;
  const logHtml = lastLog ?
    `<p><b>Protocol:</b> ${lastLog.protocol} &nbsp; <b>Encoding:</b> ${lastLog.encoding} &nbsp; <b>TTL:</b> ${lastLog.ttl}</p>
    <p><b>Segments sent:</b> ${lastLog.sent} &nbsp; <b>Delivered:</b> ${lastLog.delivered} &nbsp; <b>Lost:</b> ${lastLog.lost} &nbsp; <b>Retransmitted:</b> ${lastLog.retransmitted}</p>
    <p><b>Outcome:</b> ${lastLog.success ? 'Message delivered successfully' : (lastLog.ttlDropped ? 'Packet dropped — TTL expired' : 'Incomplete delivery')}</p>` :
    '<p>No simulation has been run yet in this session.</p>';

  const win = window.open('', '_blank');
  win.document.write(`<!DOCTYPE html><html><head><title>Lab Report</title><style>
    body{font-family:Georgia,serif; max-width:720px; margin:40px auto; color:#1a2233; line-height:1.6;}
    h1{font-size:20px; border-bottom:2px solid #333; padding-bottom:8px;} h2{font-size:15px; margin-top:24px;}
    table{width:100%; border-collapse:collapse; margin:12px 0;} td{padding:5px 0; border-bottom:1px solid #ddd;}
    .muted{color:#666; font-size:12px;}
    </style></head><body>
    <h1>${esc(title)}</h1>
    <table><tr><td><b>Student Name</b></td><td>${esc(name)}</td></tr><tr><td><b>Student ID</b></td><td>${esc(sid)}</td></tr>
    <tr><td><b>Date</b></td><td>${new Date().toLocaleString()}</td></tr>
    <tr><td><b>Model</b></td><td>${currentModel}</td></tr></table>
    <h2>Objective</h2><p>To simulate and observe data communication across the OSI/TCP-IP layers, including encapsulation, routing, and error handling, using an interactive network simulator.</p>
    <h2>Simulation Results</h2>${logHtml}
    <h2>Observations</h2><p>${esc(obs).replace(/\n/g, '<br>')}</p>
    <h2>Conclusion</h2><p>The simulation demonstrated the layer-by-layer journey of data from sender to receiver, including the effects of the configured network conditions on delivery.</p>
    <p class="muted">Generated by Inside the Wire — ${new Date().toISOString()}</p>
    </body></html>`);
  win.document.close();
  win.focus();
  win.print();
}